### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by gixousiyq** [n00b69/woa-helper#10]
kalbs could never reach its level of perfect UI design, Optimized app, Threads, No sogware, Stolen device pictures

**Comment by Xhdsos** [comment]
Niger

**Comment by gixousiyq** [comment]
@Xhdsos I like that country, Very kind people and very cool nature!

**Comment by Xhdsos** [comment]
> @Xhdsos I like that country, Very kind people and very cool nature!

Sak balls my country

**Comment by gixousiyq** [comment]
@realfooking

**Comment by Xhdsos** [comment]
хех...)
#кукловод #людипешки #хех #убийца #манипулятор #выжалкие #манипуляция #жестокая #тихоня #интересы #убийца #хех #держувстрахе #королева #богиня #красныйфлаг #бойтесь #выглупые #марионетки #вымоипешки #жалкиепешки #глупыемарионетки #дазайкинни #мненуженпсихолог #слушайсяменя #бойтесь #лучшая #antahable #дазайлучший #яубила18человекбыстроибезсожаления #скрываюэмоции #вырабы #подчиняйтесь #выкринж #манипуляторша #бегите #злая #вытакиесмешные #скобкизакрываютсяскобкизакрываются #убиваюлюдей #пытаю #скобочка #жертвы #приступник #милая #наивные #глупые #могупостоятьзасебя #серыемышки #маньяк #ялучшаядевушка #уваспроблемы #хобби #людименяются #дноклассники #сталкерша #яндере #мояличность #притворяюсь #дьявол #сатана #месть #расправа #сплетни #разрушувашужизнь  #уродка #менявселюбят #выникто #самаякрасивая #крашиха #бэдбиач #завидуйтемолчка #королевашколы #выничтожество #никакойпощады #плачь #доведудосамоубийства #несвязывайтесьсомной #непослушныепешки #досталанож #вымненичегонесделаете #криминал #оскорбления #пофигизм #страх #ум #злость #психология #ревнивая #обиженка #собственница #получаювсечтозахочу #рекомендации #обида #нож #доверчивыепешки #могууправлятьвсеми #моислуги #контролируюлюдей #гений #сераятолпа #издеваюсьнадвсеми #хейтеры #страх #пистолет #топор #держувстрахе #паралич #припадки #психичка #тысука #ялегенда #ябудупытатьтебядосмерти #перережугорло #вскробвены #тымой #янастоящийгуль #выфейки #канеки #тетрадьсмерти #смертныеуроды #уведутвоегопарнябудтоявоенкомат #выбудетемерты #танцуюнатвоеймогиле #тытруп #богатая #фенибут #наглаталасьтаблеток #вытакиеклоуны #хахахаясмеюсьсвас #нервы #нервныйсрыв #слушайтесьменя #тиран #терарист #грубая #никогонеуважаю #ярость #причиняюболь #пылаюгневом #бешенство #суровоя #холодная #терпениелопнуло #безумие #пощечина #перегнулипалку #яростнаясука #унижения #достоинство #вытерпилы #выпосмешище #враги #драка #забивы #война #смерть #дикая #артист #боты #можнопрочитатьтебякаккнижку #кукольник #правокатор #испугала #факъю #ад #ямогучая #бегите #вытрусы #жадина #ягрубая #ложь #дерзкая #заяизрая #горе #обман #скам #бу #повесилась
#никотиноваязависимость #сталалучше #пристрелись #достаюревольер #черт #дазайлучший #ненавижувас #уменявсехорошо #покинулачат #бросаю #одиночество #грусть #отвратительно #норм #лезвие #пуля #япотерялачувства #недоступная #пустотавнутри #этоконец #вычмо #бью #депрессия #влюбилавсебявсюшколу #результатыманипуляций #сигареты #вызаебалименя #прыгайсмоста #отрежутебеконечности #разобьютебесердце #живойтруп #бесконечность #интроверт #двадцатьдватридцатьодин #тымогила #гробы #похоронюзаживо #смирись #тымоясобака #яумнеетебя #ялучшетебя #тыпаскуда #гнида #вылохушки #стерва #гучифлипфлап #идиот #кретин #пошелнахер #яблююотвас #целуйтемнепятки #любитеменяжалкиепешки #выуроды #вызалупари #выочкуны #ненавижувасхейтеры #психологическийтрюк #нахожуподходклюдям #убилапервогочеловекавшестьлет #збежаластюрьмытрираза #мамабоитсяменя #учителямоипешки #непослушнаяпешка #выблохастыепсы #вашеместоупараши #умритевболоте #канававашдом #хорошаяпешка #преданнаяпешка #непослушнаяпешка #наказана #лучшийманипулятор #молчать #явашапринцесса #вамповезлосомной #всехотятсомнойдружить #всехотятменяобнять #якотораянелюблюприкосновенияиманипулируюими #выпешкивмоейбольшойигре #большаяигра #уваснетмнения #главнаяжертватихоня #выбезменяникто #таквышло #пощадынебудет #ножужеутвоегогорла #ярастопчутебя #хахахахх #жалкиесущества #букашки #работайтенаменя #ясказалавысделали #никакихпретензий #идинахуйхуесос #довелапсихолога #доведудопсихолога #психушка #психиатр #даятакбогатаияэтонескрываю #вытупозамнойповторяете #доели #ямамми #люблюхорошихпешек #мстительная #япомнювсезлоотвас #пришловремярасправы #бьюпосуду #ссадины #порезы #синяки #гимотомы #петля #отрезалаголовы #готоваидтипоголовам #чикатило #ялюблючикатилоидазая #дочьдазая #помотрошуиброшу #вызависимыотменя #вымямли #крыса #выменянепонимаете #боль
